version: "2.7"

services:
  volcan:
    build: .
    env_file: .env
    environment:
      API_BIND: 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/config/.env:ro
      - ./config.yml:/config/config.yml:ro
    restart: unless-stopped
